local windline = require('windline')
local effects = require('wlanimation.effects')
local HSL = require('wlanimation.utils')
require('wlsample.airline')
-- require('wlsample.airline_anim')
-- require('wlsample.airline_luffy')
-- require('wlsample.basic')
-- require('wlsample.wind')
-- require('wlsample.bubble')
-- require('wlsample.bubble2')
-- require('wlsample.simple')
-- require('wlsample.vscode')
-- require('wlsample.rainbow')
